/**
 * data.js
 */

const json = `[{"id":1,"first_name":"Micky","last_name":"Cavilla","email":"mcavilla0@1und1.de","gender":"Female","salary":4674},
{"id":2,"first_name":"Shaylah","last_name":"Junkin","email":"sjunkin1@umich.edu","gender":"Female","salary":6600},
{"id":3,"first_name":"Esma","last_name":"Eden","email":"eeden2@shop-pro.jp","gender":"Female","salary":3078},
{"id":4,"first_name":"Nonie","last_name":"Yvens","email":"nyvens3@addtoany.com","gender":"Female","salary":4645},
{"id":5,"first_name":"Celeste","last_name":"De Giovanni","email":"cdegiovanni4@seesaa.net","gender":"Genderfluid","salary":3017},
{"id":6,"first_name":"Hamil","last_name":"Cherryman","email":"hcherryman5@studiopress.com","gender":"Male","salary":4502},
{"id":7,"first_name":"Barret","last_name":"Loutheane","email":"bloutheane6@google.it","gender":"Male","salary":6693},
{"id":8,"first_name":"Emiline","last_name":"Makey","email":"emakey7@weibo.com","gender":"Female","salary":7141},
{"id":9,"first_name":"Vin","last_name":"Jarmyn","email":"vjarmyn8@weather.com","gender":"Male","salary":8882},
{"id":10,"first_name":"Donny","last_name":"Hinsche","email":"dhinsche9@wp.com","gender":"Genderfluid","salary":7359},
{"id":11,"first_name":"Silvia","last_name":"Leach","email":"sleacha@php.net","gender":"Female","salary":3462},
{"id":12,"first_name":"Ilyssa","last_name":"Elcombe","email":"ielcombeb@wikipedia.org","gender":"Female","salary":6079},
{"id":13,"first_name":"Job","last_name":"Whittle","email":"jwhittlec@usda.gov","gender":"Male","salary":8462},
{"id":14,"first_name":"Burch","last_name":"Benzi","email":"bbenzid@loc.gov","gender":"Male","salary":4965},
{"id":15,"first_name":"Bent","last_name":"Alps","email":"balpse@typepad.com","gender":"Polygender","salary":8846},
{"id":16,"first_name":"Mohammed","last_name":"McMickan","email":"mmcmickanf@csmonitor.com","gender":"Male","salary":7327},
{"id":17,"first_name":"Floria","last_name":"Britland","email":"fbritlandg@globo.com","gender":"Female","salary":4317},
{"id":18,"first_name":"Meridith","last_name":"Rogeon","email":"mrogeonh@artisteer.com","gender":"Female","salary":7093},
{"id":19,"first_name":"Gwenore","last_name":"Mincher","email":"gmincheri@comsenz.com","gender":"Female","salary":7139},
{"id":20,"first_name":"Wilmar","last_name":"Hampton","email":"whamptonj@amazon.com","gender":"Male","salary":8908},
{"id":21,"first_name":"Doug","last_name":"Emslie","email":"demsliek@nasa.gov","gender":"Male","salary":8059},
{"id":22,"first_name":"Sayre","last_name":"Smeal","email":"ssmeall@webnode.com","gender":"Female","salary":9505},
{"id":23,"first_name":"Vanessa","last_name":"Sowden","email":"vsowdenm@privacy.gov.au","gender":"Female","salary":5487},
{"id":24,"first_name":"Anni","last_name":"Tertre","email":"atertren@harvard.edu","gender":"Female","salary":9892},
{"id":25,"first_name":"Haslett","last_name":"Esome","email":"hesomeo@si.edu","gender":"Genderqueer","salary":7947},
{"id":26,"first_name":"Granny","last_name":"Romand","email":"gromandp@seesaa.net","gender":"Male","salary":5918},
{"id":27,"first_name":"Myrle","last_name":"Brackenbury","email":"mbrackenburyq@ezinearticles.com","gender":"Female","salary":4056},
{"id":28,"first_name":"Zaneta","last_name":"Batcock","email":"zbatcockr@bizjournals.com","gender":"Female","salary":5470},
{"id":29,"first_name":"Joshuah","last_name":"Jecock","email":"jjecocks@vk.com","gender":"Male","salary":5873},
{"id":30,"first_name":"Mathian","last_name":"Joyson","email":"mjoysont@youtu.be","gender":"Male","salary":6594}]`;